// Components
export { default as Accordion } from "./src/components/widgets/Accordion/index.astro"
export { default as Article } from "./src/components/landmarks/Article/index.astro"
export { default as Body } from "./src/components/page/Body/index.astro"
export { default as Byline } from "./src/components/landmarks/Article/Byline/index.astro"
export { default as Footer } from "./src/components/landmarks/Footer/index.astro"
export { default as Head } from "./src/components/page/Head/index.astro"
export { default as Header } from "./src/components/landmarks/Header/index.astro"
export { default as Html } from "./src/components/page/Html/index.astro"
// export { default as LinkedData } from "./src/components/meta/LinkedData/index.astro"
export { default as Main } from "./src/components/landmarks/Main/index.astro"
// export { default as Meta } from "./src/components/meta/Meta/index.astro"
export { default as Nav } from "./src/components/landmarks/Nav/index.astro"
export { default as Section } from "./src/components/landmarks/Section/index.astro"
export { default as Subheading } from "./src/components/landmarks/Section/Subheading/index.astro"
export { default as Subtitle } from "./src/components/landmarks/Article/Subtitle/index.astro"
export { default as Title } from "./src/components/landmarks/Article/Title/index.astro"

// Metadata
export { default as Boolean } from "./src/components/metadata/Boolean/index.astro"
export { default as Email } from "./src/components/metadata/Email/index.astro"
export { default as Integer } from "./src/components/metadata/Integer/index.astro"
export { default as MonetaryAmount } from "./src/components/metadata/MonetaryAmount/index.astro"
export { default as Number } from "./src/components/metadata/Number/index.astro"
export { default as RealNumber } from "./src/components/metadata/RealNumber/index.astro"
export { default as String } from "./src/components/metadata/String/index.astro"
export { default as Telephone } from "./src/components/metadata/Telephone/index.astro"
export { default as TitleOfWork } from "./src/components/metadata/TitleOfWork/index.astro"
export { default as Url } from "./src/components/metadata/Url/index.astro"

// Temporal
export { default as Duration } from "./src/components/temporal/Duration/index.astro"
export { default as Instant } from "./src/components/temporal/Instant/index.astro"
export { default as PlainDate } from "./src/components/temporal/PlainDate/index.astro"
export { default as PlainDateTime } from "./src/components/temporal/PlainDateTime/index.astro"
export { default as PlainMonthDay } from "./src/components/temporal/PlainMonthDay/index.astro"
export { default as PlainTime } from "./src/components/temporal/PlainTime/index.astro"
export { default as PlainYearMonth } from "./src/components/temporal/PlainYearMonth/index.astro"
export { default as TimeZone } from "./src/components/temporal/TimeZone/index.astro"
export { default as YearWeek } from "./src/components/temporal/YearWeek/index.astro"
export { default as ZonedDateTime } from "./src/components/temporal/ZonedDateTime/index.astro"

// Scripts
export { default as EnhancedAccordion } from "./src/components/widgets/Accordion/enhance.astro"
